FIx "could not establish connection" error on _tryload()
At this point of the code, no listener is registered. For this reason,
this line causes the following exception:

> error: could not establish connection. receiving end does not exist

Fix this issue by avoid broadcasting on initial loading.

Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>